-- Add dual-CL VaR columns (legacy single-CL columns dropped).

ALTER TABLE position_var
    ADD COLUMN IF NOT EXISTS mg_std      NUMERIC,
    ADD COLUMN IF NOT EXISTS var_95      NUMERIC,
    ADD COLUMN IF NOT EXISTS var_99      NUMERIC,
    ADD COLUMN IF NOT EXISTS es_95       NUMERIC,
    ADD COLUMN IF NOT EXISTS es_99       NUMERIC,
    ADD COLUMN IF NOT EXISTS mg_var_95   NUMERIC,
    ADD COLUMN IF NOT EXISTS mg_var_99   NUMERIC,
    ADD COLUMN IF NOT EXISTS mg_es_95    NUMERIC,
    ADD COLUMN IF NOT EXISTS mg_es_99    NUMERIC;
